config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'static_pages#index'
  resources :static_pages, only: [:index] do
    collection do
      get :export
    end
  end
end

app/models/account_information.rb
class AccountInformation < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :account_information, dependent: :destroy
  has_many :sales, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'csv'

  def index
    @users = User.all
    @sales = Sale.all
    @account_informations = AccountInformation.all
  end

  def export
    @account_informations = AccountInformation.all

    respond_to do |format|
      format.csv { send_data generate_csv(@account_informations), filename: "CSVサンプル.csv" }
    end
  end

  private

  # GMOあおぞらネット銀行指定形式
  def generate_csv(account_informations)
    csv_data = CSV.generate(encoding: 'Shift_JIS') do |csv| # 文字コードをShift_JISに指定する必要があります。
      account_informations.each do |account_information|
        sale = Sale.find_by(user_id: account_information.user.id) # 振込金額を先に検索しておきます
        # この時の値の呼び出し方等はアプリに応じて調整してください。

        # GMOあおぞらネット銀行指定形式では、下記項目がこの順番で並んでいる必要があります。
        # 他細かいデータ形式は公式のPDF参照。
        csv << [
          account_information.bank_code,      # 銀行コード　：先頭の0は省略せず4桁で表記
          account_information.branch_code,    # 支店コード　：先頭の0は省略せず3桁で表記
          account_information.deposit_type,   # 預金種目　　：1(普通),2(当座),4(貯蓄)の数値で表記
          account_information.account_number, # 口座番号　　：先頭の0は省略せず7桁で表記
          account_information.bank_account,   # 受取口座名義：半角ｶﾀｶﾅで表記
          sale&.price,                        # 振込金額
          nil,                                # 手数料負担区分（空欄）
          nil,                                # 振り込み依頼人（空欄）
          nil                                 # EDI情報（空欄）
        ]
      end
    end
  end

end

app/helpers/account_informations_helper.rb
module AccountInformationsHelper
  def translate_deposit_type(deposit_type)
    case deposit_type
    when 1
      '普通'
    when 2
      '当座'
    when 4
      '貯蓄'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light" lang="ja">
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="flex flex-col space-y-24 mb-10">
  <%= link_to 'CSVエクスポート', export_static_pages_path(format: :csv), class: 'btn btn-primary w-40' %>

  <div class="overflow-x-auto">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>name</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each_with_index do |user, index| %>
          <tr>
            <th><%= index + 1 %></th>
            <td><%= user.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="overflow-x-auto">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>user</th>
          <th>price</th>
        </tr>
      </thead>
      <tbody>
        <% @sales.each_with_index do |sale, index| %>
          <tr>
            <th><%= index + 1 %></th>
            <td><%= sale.user.name %></td>
            <td><%= sale.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="overflow-x-auto">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>銀行コード</th>
          <th>支店コード</th>
          <th>預金種目</th>
          <th>口座番号</th>
          <th>受取口座名義</th>
        </tr>
      </thead>
      <tbody>
        <% @account_informations.each_with_index do |account_information, index| %>
          <tr>
            <th><%= index + 1 %></th>
            <td><%= account_information.bank_code %></td>
            <td><%= account_information.branch_code %></td>
            <td><%= translate_deposit_type(account_information.deposit_type) %></td>
            <td><%= account_information.account_number %></td>
            <td><%= account_information.bank_account %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/static_pages/top.html.erb
<div class="p-4 space-y-2">
  <button class="btn btn-primary">Daisy</button>
</div>